version: "3.8"

services:
  minio:
    image: quay.io/minio/minio
    container_name: minio
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      # Todo: store env variables
      MINIO_ROOT_USER: ROOTNAME
      MINIO_ROOT_PASSWORD: CHANGEME123
      MINIO_NOTIFY_WEBHOOK_ENABLE_API: on
      MINIO_NOTIFY_WEBHOOK_ENDPOINT_API: http://host.docker.internal:3000/api/webhook/recipe/image
      MINIO_NOTIFY_WEBHOOK_AUTH_TOKEN_API: MINIO
      MC_DEBUG: true
    volumes:
      - ~/minio/data:/data
    command: server /data --console-address ":9001"
